### ISSUE TITLE
Applying slit function - change of wavelength range

### ISSUE THREAD

**Issue by minouHub** [radis/radis#1]
When using s.applyslit(), the convolution change the range of the calculation. I know you already solved the problem before, but obviously not on this version.

Minou

**Comment by erwanp** [comment]
It's actually on purpose: The wings of the spectrum are not valid after the convolution (because we don't know what lines are out of the range) so they are discarded and only the valid part is kept.

It could be added as an option in apply_slit to keep the same range, but it shouldn't be the default behavior

**Comment by minouHub** [comment]
Alright, so I should calculate my spectrum on a wider wave-range to take that into account.
