### ISSUE TITLE
Improve definition of width-grid resolution (res_L, res_G)

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#115]
With the manuscript draft being updated, we now have a much better handle on how to precisely define the errors in the width-grid for the "DLM"-approach. It would be good to propagate these updates to the RADIS code, but some executive decisions have to be made on how to implement it.

There are basically three candidates of how the user could specify the desired error:

- **`p`**                                                     -> _relative increase between two width-gridpoints_
- **`log_p`** = np.log(p)                            -> _actual step-size of the logarithmic width-grid_
- **`err_rms`** = RMS[Y_i]*np.log(p)/12    -> _contribution to RMS-error by a single line._ 
(The factor 1/12 = 1/2 x 1/6, where 1/6 comes from integrating the grid-alignment assuming uniform distribution between 0 and 1)

Each has their own advantage, namely:

- **`p`**: unambiguous what is meant, and makes sense from a human perspective (e.g. `p = 1.2` means 20% increase between gridpoints)
- **`log_p`**: equally unambiguous, but perhaps makes less sense from a human perspective (e.g. what really does `log_p = 0.2` mean?). Advantage is that when `log_p` is closer to zero, it means higher resolution, which perhaps is more intuitive.
- **`err_rms`**: Makes most sense from human point of view, and resolution also gets better as `err_rms` gets closer to zero. Problem is that choosing the RMS-error as the defining error measure is somewhat arbitrary, and depending on the kind of weight used (1,2, or 3), the same value of `err_rms` will lead to different `p` and `log_p` values, which the user may not be aware of (but perhaps equally possibly they do not care about)

Anyway so that's a decision that has to be made. My personal preference is in the presented order (with **`p`** most favorable), but of course I'd like to hear everyone's thoughts.

**Comment by erwanp** [comment]
@dcmvdbekerom is this one still up-to-date? I can look at it tomorrow !

**Comment by dcmvdbekerom** [comment]
It is! And while working on it more I have changed my mind, I think **log_p** should be the value used! This is because I found it's really convenient to have a parameter that gets better as it gets closer to 0, instead of when it gets closer to 1.

**Comment by erwanp** [comment]
I actually like `err_rms` better, not only because it is also better as it gets closer to 0, but because I think that it gives the user a great sense of control over what is happening. 

I considered doing the same with the linestrength cutoff for instance : rather than setting an arbitrary line cutoff (and being told / warned if the error is too high, as done now), users could start with the error they can effort, and the code adjusts the line cutoff.

**Comment by dcmvdbekerom** [comment]
There are a couple of issues with `err_rms` that make it unsuitable IMHO.
For one, when reporting what settings were used in papers, different authors may use different definitions of `err_rms` and there's no telling them apart to the audience, this is why I would much prefer `log_p` (or `p` for that matter) which is much better defined and more unambiguous.

There are two more problems with using `err_rms`: one is that the RMS-error is a function of the w_L/w_G ratio, which of course varies wildly for all the lines in the database and even varies with different conditions, so it's not clear at what ratio to evaluate this error (and if we decide on one, if this is relevant for the spectrum the user is going to plot). Moreover, with the optimized weights, _the Lorentzian rms-error reduces when log-pG is reduced and vice versa_

To that last point, check out the graph below where the top plots are for log_pG = log_pL = 0.2 and bottom are log_pG = 0.1, log_pL = 0.2. Notice how for the optimized weights the Lorentzian error decreases with reduced log_pG.

![rms_errors](https://user-images.githubusercontent.com/7279972/89591530-6562a600-d818-11ea-9cee-82ebd5b93b14.png)

So then the question becomes what RMS-error even to assign to a certain value of log_pG or log_pL.

What about we use log_pG and log_pL as input, but then print a proxy/prediction of some rms-error measure?

**Comment by dcmvdbekerom** [comment]
One more thing I thought I'd add to this discussion; the errors with the "DLM"-approach are so much smaller that wonder if any user without a thorough understanding of the underlying mechanisms would ever need to change the grid-resolution. 

To clarify my point, I cleaned up the plot above a bit and compared the errors with those of Whiting. Using `log_pG = 0.1` and `log_pL = 0.2` (close to the current `res_G = 0.01`, `res_L = 0.01`, which yields `log_pG = 0.14` and `log_pL = 0.22`), the errors are smaller than Whiting's over almost the entire range, with the best case having up to almost a ~100x smaller error. 

Whiting's approximation is very popular and a lot of people "settle" for this kind of precision at the moment (either knowingly or unknowingly). So if we would use default values of `log_pG = 0.1` and `log_pL = 0.2` (which, again, is close to what they are now), then realistically I don't think they ever need to be changed.

In the plots I also added "pure G/L", which is the "optimization" used in the current implementation in RADIS, given by `a = (1-p^-tau)/(1-p^-1)` (it looks different in the code but it comes out to this). This weight minimizes the error for the pure Gaussian and the pure Lorentzian. As can be seen, if the lineshape is not a perfect G or L, it actually performs worse than the simple weights given by `a = tau`, while for a pure G or L it performs only marginally better.

(Linear y-axis)
![rms_errors](https://user-images.githubusercontent.com/7279972/89679887-f2146f00-d8bf-11ea-940a-d81946cdfe90.png)

(Logarithmic y-axis):
![rms_errors_log](https://user-images.githubusercontent.com/7279972/89680107-4c153480-d8c0-11ea-8ae0-a947e9701705.png)

**Comment by erwanp** [comment]
First, well done : the comparison with Withing is very insightful, and very promising ! 

I still believe that `err_rms` is probably the most important parameter for the user, but maybe SpectrumFactory and the current implementation is not the right place to make it an input. 

Your main points against `err_rms` is that they are 1. not well defined nor reproducible 2. changing with the line and 3. too small anyway. 
1. I actually think that few people look into computational parameters when trying to reproduce results (at least, not enough!). Also, sometimes they cannot do otherwise, as different codes may use different parameters. Using `err_rms` would actually allow users to focus on the physical parameters (ex : uncertainty on the temperature) rather than on computational parameters themselves. And I like that. 
2. is very true, but we have to deal with it : if we want to give an a posterior approximation of the error as you seem to suggest, it will arise again. 
3. The fact we're up to 100x better than Whiting doesn't only mean that users shouldn't matter : it also gives us the opportunity to use a sparser grid, which may be even faster !

In general, I can imagine a software where you do not need to specify any grid, including the wavenumber grid : you would just specify a maximum error (on the radiance) that you can afford, and everything would be taken into account automatically. 

However, as I said in the introduction, SpectrumFactory and this current implementation may not be the right place for that : 
1. first, let's keep it simple.
2. having smart optimization routines is neat, but in general I rather want to have them separate from the core calculation. So we could introduce an Optimizer as another optimizatino routine of SpectrumFactory, or in a higher-level function such as calc_spectrum, that makes the guesses, and sends the arguments to SpectrumFactory. 

```
User specifies error >> Optimizer guesses log_pG, log_pL, wstep, lineshape method, cutoff and all the parameters we can think of >> SpectrumFactory runs the calculation >> Optimizer evaluates the error >> Spectrum is returned to the user. 
```

Conclusion : let's use log_pG and log_pL.

**Comment by dcmvdbekerom** [comment]
Implemented in https://github.com/radis/radis/pull/116
