### ISSUE TITLE
negative absorbance / too coarsed spectral grids 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#186]
### 🐛 Describe the bug

This error was detected by @Anjum48 in the [RADIS atmosphere example](https://github.com/radis/radis-examples) (see https://github.com/radis/radis-examples/issues/4)

```

  File "d:\github\radis\radis\lbl\factory.py", line 798, in eq_spectrum
    transmittance_noslit = exp(-absorbance)

RuntimeWarning: overflow encountered in exp
```

The unexpected thing is that the overflow only happens with the new LDM algorithm (on CPU), and not with the historical method. @dcmvdbekerom  

### 🖥 Steps To Reproduce

Here is a minimal example with conditions taken from the atmosphere example 

```

from radis import calc_spectrum
from warnings import catch_warnings, simplefilter

# Physical parameters                  
wmin = 400                       #: wavenumber min
wmax = 900                       #: wavenumber max
x_CO2 = 400e-6     #: float: mole fraction of CO2 

# Spectral Computation parameters
wstep = 0.003                    # wavenumber step (cm-1)

# %% Get Spectral line database
with catch_warnings():
    simplefilter('error', category=RuntimeWarning)
    calc_spectrum(wavenum_min=wmin, 
                 wavenum_max=wmax,
                 molecule='CO2',
                 isotope='1,2,3',
                 verbose=3,
                 wstep=wstep,
                 broadening_max_width=3,
                 warnings={'MissingSelfBroadeningWarning':'ignore'},
                 export_lines=False,
                 Tgas=234.25,
                 pressure=0.00646122,
                 path_length=100000,   #  cm
                 # optimization=None,      # if None, no error !
                 )
```

By investigating, we find out that the LDM method sometimes produces **negative** absorbance numbers (?) :

```
! %debug
! absorbance.min()
-680251.6244835826
```

which in turn raise an overflow.

**Comment by dcmvdbekerom** [comment]
Interesting... I wonder if this is an issue with the LDM algorithm, or rather with the optimized weights of the algorithm.
Can you try the keyword ```optimization = "simple"``` and see if this solves the issue? (I don't have a computer with RADIS installed near me atm)

**Comment by erwanp** [comment]
More update & further investigation :  

The problem comes from a too coarsed spectral grid (`wstep` at 0.003 cm-1 is too large for the pressures considered) . Without the LDM method the convolution uses an analytical Voigt profile (Whiting).  With the optimization the convolution uses an FFT. The FFT simply performs much worse with too coarsed grids. At 0.0005 cm-1 both methods perfectly resolve the spectra. 

![image](https://user-images.githubusercontent.com/16088743/105229612-815ac980-5b64-11eb-8c82-974295f8cc73.png)


Minimal code : 

```

import matplotlib.pyplot as plt

conditions = {
    "molecule":"CO2",
    "isotope":1,
    "wavenum_min":667.5,
    "wavenum_max":667.7,
    "pressure":0.00646122,
    "Tgas":234.25,
    "path_length":100000,
    "broadening_max_width":3,
    "warnings":{'MissingSelfBroadeningWarning':'ignore'},
}


plt.figure()
for wstep in [0.0005, 0.003]:
    s1 = calc_spectrum(**conditions,
                       wstep=wstep,
                       optimization=None,      # if None, no error !
                       name=f'voigt (dw {wstep}cm-1)'
                       )
    s2 = calc_spectrum(**conditions,
                       wstep=wstep,                 
                       optimization='min-RMS',      # if None, no error !
                       name=f'fft (dw {wstep}cm-1)'
                 )
    
    s1.plot('abscoeff', nfig='same', color='k', lw=wstep*1000)
    s2.plot('abscoeff', nfig='same', color='r', lw=wstep*1000)
    
plt.ylim(ymax=40)
plt.legend()
```

The only question is :  what do we do about it ? 
- a previously suggested feature was to have an automatic wavenumber spacing: ~10 wsteps / FWHM
- we could at least raise a warning / error after computing the broadenings and before resolving the lineshapes, if criteria above is not fulfilled. 

Note that if using the direct "convolve" broadening_method (instead of approximate analytical Voigt), a warning would indeed trigger in the present case, based on [checking the lineshape integral](https://github.com/radis/radis/blob/develop/radis/lbl/broadening.py#L1089) : 

> d:\github\radis\radis\misc\warning.py:243: CollisionalBroadeningWarning: Large error (542.1%) in pressure broadening. Increase broadening width / reduce wstep. Use .plot_broadening() to visualize each line broadening
  warnings.warn(WarningType(message))
d:\github\radis\radis\misc\warning.py:243: GaussianBroadeningWarning: Large error (753.3%) in Doppler broadening. Increase broadening width / reduce wstep. Use .plot_broadening() to visualize each line broadening
  warnings.warn(WarningType(message))

This was a cool/slow check, but not implemented for the analytical Voigt nor the FFT.
The suggested check above would be much faster (we're not computing integrals, only comparing an array of calculated widths).

**Comment by erwanp** [comment]
@dcmvdbekerom so no problem with the LDM algorithm itself ! 

> (I don't have a computer with RADIS installed near me atm)

There is always RADIS-Lab https://radis.github.io/radis-lab/  around for quick checks now ! :)

**Comment by dcmvdbekerom** [comment]
Ah so this is the ringing that we described in the paper; I would have thought this was just a mathematical curiosity of trivial importance, but it turns out it can break the code!

Since ringing only occurs when dv ~ wL,wG, I think the best solution would be to always make sure that the smallest width in the grid is has wL=0, so the FT would be a constant  (this is almost never an issue for wG). This way perhaps the lineshape approximation is a bit course because the grid stepsize is a bit larger, but at least this will prevent ringing and negative values. It also means that the step-size is not constant anymore, but this is not an issue for the RADIS implementation because it uses np.interp() to find the indices.

**Comment by dcmvdbekerom** [comment]
Ok there's a better solution, let me first explain what's going on for everyone's benefit:

When the lineshape is broad with respect to the grid spacing, the FT of the line is very narrow. This means that at high frequencies in the FT-domain, the intensity goes to zero, and thus the lineshape is nicely represented: No information is lost in the FT-process.

If the lineshape is _much_ narrower than the grid spacing, then the FT will be just constant everywhere, and the lineshape will be represented by a single point having a non-zero value (the discrete equivalent of a Dirac delta peak). Also no issues.

When the lineshape width is of the same order of the grid spacing, the FT does not completely go to zero at the highest frequencies, as depicted by the blue line in the figure below:
![Folding](https://user-images.githubusercontent.com/7279972/105321408-45336300-5b7c-11eb-8004-d844b3c59c71.png)

If that's the case, it's as if the actual FT-spectrum is multiplied by a rectangular window function, so the lineshape in the real domain is convolved with a sinc(v) function, whish is causing the negative values. This is an effect well known to occur in FTIR spectrometers.

To solve this issue, what you could do is instead of calculating the lineshapes in the FT-domain directly (as we're doing now), calculate them in the real domain and transform them to FT-domain. This will result in optimal lineshapes, but is extremely costly as it doubles the amount of FT's needed.

Instead, we can emulate the difference between our directly calculated FT-domain lineshapes and FT-transforms of the real lineshapes, this is a process called folding, and is depicted by the orange and green curves in the figure. Whenever the FT-domain lineshape hits an edge, just reflect it and add the rest to the spectrum (i.e. fold it). Keep doing this until the leftover is 'zero' or the profile is sufficiently straight such that the FT back to the real domain is accurately represented by a discrete Dirac delta peak.

The downside is that we have to introduce some arbitrary threshold below which we consider the profile values "zero", to prevent folding infinitely many spectra. Still, I expect on average the number of folds will be "reasonable" (<10, say), so this should not introduce a noticeable hit in performance,

**Comment by erwanp** [comment]
@dcmvdbekerom remark on this :

> If the lineshape is much narrower than the grid spacing, then the FT will be just constant everywhere, and the lineshape will be represented by a single point having a non-zero value (the discrete equivalent of a Dirac delta peak). Also no issues.

For transmission spectra this may be fine : you can use a coarse spectral grid if your experiments are not very resolved. 
However, for emission spectra, having a lineshape smaller than the spectral grid is a source of error : you wouldn't be able to resolve the radiative transfer equation properly if multiple lines are nearby.  If you're not in an optically thin case, you could overestimate the radiance by a lot !

**Comment by dcmvdbekerom** [comment]
The folding was implemented in my latest [PR](https://github.com/radis/radis/pull/190/commits)
The `simple` weights now behave the same way as the traditional lineshapes. I think this is very desirable from a user persepective. The folding threshold is set to 1e-6, which is very low so I don't imagine anyone ever needs to adjust it, but it's just so cheap to compute a bit more folds so might as well.

However, while there was indeed some discrepancy between `simple` weight LDM optimization and conventional method before (which is now fixed), the bigger issue was (and still is) that the `min-RMS` weights don't work at low resolution. This makes sense, because the subtleties I laid out above were not included in the optimization process. I'm curious to see if this can be fixed, but until that time I would suggest to use `simple` over `min-RMS` whenever possible. At the very least, `min-RMS` should not be the default optimization method.

Here's the earlier example with the updated code at wstep = 0.003 cm-1:
![image](https://user-images.githubusercontent.com/7279972/105621257-7f8a4380-5dba-11eb-9099-a0da8d551675.png)

```

import matplotlib.pyplot as plt
from radis import calc_spectrum

conditions = {
    "molecule":"CO2",
    "isotope":1,
    "wavenum_min":667.5,
    "wavenum_max":667.7,
    "pressure":0.00646122,
    "Tgas":234.25,
    "path_length":100000,
    "broadening_max_width":3,
    "warnings":{'MissingSelfBroadeningWarning':'ignore'},
}

plt.ion()
plt.figure()

wstep = 0.003 #cm-1

s1 = calc_spectrum(**conditions,
                   wstep=wstep,
                   optimization=None,      # if None, no error !
                   name=f'voigt'
                   )
s2 = calc_spectrum(**conditions,
                   wstep=wstep,                 
                   optimization='simple',      # if None, no error !
                   name=f'fft (simple)'
             )
s3 = calc_spectrum(**conditions,
                   wstep=wstep,                 
                   optimization='min-RMS',      # if None, no error !
                   name=f'fft (min-RMS)'
             )

s1.plot('abscoeff', nfig='same', color='k', lw=3)
s2.plot('abscoeff', nfig='same', color='r', lw=1)
s3.plot('abscoeff', nfig='same', color='b', lw=2)
    
plt.ylim(ymax=20)
plt.legend()

```

**Comment by dcmvdbekerom** [comment]
I compared the `min-RMS` of a lightweight code I have and it also doesn't match, but isn't nearly as bad as the one implemented in RADIS, suggesting there is something else that's wrong.

One thing I noticed is that when the LDM is made, the length of `len(wavenumber_calc)=1068`, but the wavenumber axis that is used for plotting is only `68` long. This suggests we're adding lines that we can't see.. this seems not very efficient and could run into issues when the algorithm cannot find the proper index and tries to add them anyway (at what wavenumber would they be added? no way to tell..). Any thoughts on this discrepancy? Is it a bug or a feature?

**Comment by dcmvdbekerom** [comment]
Alright, I think I have a better view of what's going on;

First of all: the `min-RMS` had bugs in it, and _that_ was the reason for the negative peaks. These have been solved in https://github.com/radis/radis/pull/190/commits. Without folding, this is what we get:

![image](https://user-images.githubusercontent.com/7279972/105625838-cd19a700-5de0-11eb-9b31-124b5bad9e05.png)

Doesn't look too bad, but if you zoom in on the peaks you _can_ still see the oscillatory behavior. With folding, but no normalization, the peak area is overestimated (we can understand this based on my previous post):
![image](https://user-images.githubusercontent.com/7279972/105625880-21bd2200-5de1-11eb-821d-685fc98914a0.png)

So we turn on normalization. Now the `simple` weights look great, but the `min-RMS` look worse than without any folding at all..!
![image](https://user-images.githubusercontent.com/7279972/105625895-4618fe80-5de1-11eb-9be6-4105dab64aca.png)

So I guess we could put in some flags that folding + normalization is used when `simple` weights are used, and neither is used with `min-RMS` weights. Having said that, I'm starting to wonder if the `min-RMS` weights are still that useful if you have to be super careful on how to use them. I'm starting to like the `simple` weights more and more.

**Comment by erwanp** [comment]
Indeed Radis automatically extends the calculated range to include nearby lines. It's a feature for extra accuracy, which ha
can also add a lot of useless computational time at low pressure because the added range is on the order of 10 cm-1.  In general I like that the default parameters ensures accuracy and that optimizations can be made by the user, rather than the other way around. 

It's hard to guess if neighbor lines should have been added or not before actually computing the spectrum. An easy way to improve it is to add a-posteriori Performance warnings, typically once you know the maximum broadening widths.

(this is not relevant here, leaving it so we can create an issue out of this comment)

**Comment by erwanp** [comment]
https://github.com/radis/radis/pull/190 merged with @dcmvdbekerom 's folding : more robust FFT lineshapes with coarse grids. 

I'll still add warnings when the grid is coarse, and then consider this issue closed.

**Comment by erwanp** [comment]
Answering https://github.com/radis/radis/issues/186#issuecomment-766315979 : 

`min-RMS` yields better accuracy but only if used properly, and is less robust than using `simple`. 

This is a case-in-point of a more general aspect of complex models / or nice performance optimizations : they shouldn't be used outside their range of validity. There are dozens of similra examples in spectroscopy codes : 
- for instance, data based on experimental fits may be more accurate than a simple model, but also more prone to large extrapolation errors if used outside the fitting domain. Think of any high-order polynomial, for instance the ones used to compute rovibrational energies. 
- same goes for the approximate analytical lineshapes.
- using HITRAN beyond 700 K ... 
- rescaling a Spectrum with different mole fractions, without recomputing pressure broadening, is also accurate only to some extent.
- etc. 

In general, it all boils down to optimization between `'accuracy'` and `'performance'`.  By default, RADIS should target something in between, i.e., not be more-accurate-than-necessary (if your experimental transmittance spectrum is low resolution, you don't need high resolution !), and never be wrong (or at least let the user know !). 

Some general guidelines for us could be : 
- Robust : should work in every conditions even beyond the ones we tested. 
- Accurate : every hypothesis should be tested _a priori_ when possible, and _a posteriori_ always.
- Informative : always tell the users what's going on. 
- Simple  :  from the end-user perspective, there should be only one main mode : `'default'`.  And maybe two extra :  `'accuracy'`, `'performance'`. 

@dcmvdbekerom if you can find another one starting with "D", the guidelines above become R.A.D.I.S. :)  

These guidelines, and in particular the systematic testing of hypothesis, could be implemented **systematically** within the code itself. For instance, similarly to how we defined a [Default](https://github.com/radis/radis/blob/6208417028b52173a185eb08f612aed7732d41c3/radis/misc/utils.py#L75) class that is used to check the inputs, any computational parameter (in the example above : the  `optimization` parameter) could be defined as a class itself,  which also implements methods to raise _a priori warnings_  and _a posteriori_ checks. Before and after computing the spectra, we would systematically run all the checks and store in the final Spectrum whether the checks/validations passed. The end-user would just have to run a `"check_valid()"` method to check that every input parameter was correct, and maybe even be given some suggestions on how to improve performance. 

This is a common pitfal of most advanced/scientific codes, and also something we should tackle seriously to let anyone, not necessarily a line-by-line spectroscopy expert, be confident in using the code. This would be quite unique for a scientific code, actually !

**Comment by dcmvdbekerom** [comment]
Well said - completely agree! I think this is issue is solved then?
(How about D - Deliberate: optimizations that sacrifice accuracy should only be applied when the user explicitly asks for it)

**Comment by erwanp** [comment]
Nice! 

Also : Robust / Accurate / Descriptive / Intuitive / Scalable.
