### ISSUE TITLE
Wavelength range of calc_spectrum != [wavelength_min, wavelength_max]

### ISSUE THREAD

**Issue by CARaDOC-Admin** [radis/radis#214]
### 🐛 Describe the bug

When using `calc_spectrum` with wavelength as inputs, we specify `wavelength_min` and `wavelength_max`.

The output wavelengths are lower than the boundaries provided to  `calc_spectrum` due to their conversion to wavenumbers and back into wavelengths.

### 🖥 Steps To Reproduce

```python
s = calc_spectrum( wavelength_min=5200, # nm
                   wavelength_max=5250, 
                   molecule='CO',
                   isotope='1,2,3',
                   pressure=1.01325,   # bar
                   Tgas=300,           # K
                   mole_fraction=0.1,
                   path_length=1,      # cm
                   verbose=False
                  )
w, I = s.get('radiance_noslit', wunit="nm", Iunit="mW/sr/cm2/nm")
print(w.min(), w.max())
```

### 🎯 Expected behavior

w.min() == wavelength_min
w.max() == wavelength_max

### 💡 Possible solutions

Make a decision if input is provided as wavelength instead of wavenumbers.

**Comment by erwanp** [comment]
Thank you for reporting !!! Similar to https://github.com/radis/radis/issues/81 ?

**Comment by gh4ag** [comment]
Absolutely!

Using `w, I = s.get('radiance_noslit', wunit="nm_vac", Iunit="mW/sr/cm2/nm")` with wunit="nm_vac", instead of wunit="nm_vac" fixes the issues.

**Comment by erwanp** [comment]
Everything happens in [_get_waveange](https://github.com/radis/radis/blob/develop/radis/lbl/factory.py#L1701)  so something is wrong in the function or when it is called. Anyway, the vacuum parameter is not taken into account. 

It's a fairly limited code, so its a good first issue.

**Comment by gagan-aryan** [comment]
I was looking this up and converted back the wavenumbers generated by [_generate_wavenumber_range](https://github.com/radis/radis/blob/develop/radis/lbl/factory.py#L1701) back to wavelengths in nm and their values are fine. 

`wavenumber_min = 1904.76190476` which corresponds to `wavelength = 5250.` and `wavenumber_max=1923.08190476` which corresponds to `wavelength=5199.98652956`

The issue seems to be with [spectrum.py](https://github.com/radis/radis/blob/develop/radis/spectrum/spectrum.py),  in the [get function](https://github.com/radis/radis/blob/3e5a7380b19bdd1adb7300922209511dba4bbce8/radis/spectrum/spectrum.py#L661) where the `medium` is passed as `air` whenever `wunit=nm`. Therefore the wavelengths are converted to their values in air. A solution to this would be to simply change the default value of `medium=vacuum` but I am not sure how other use cases would be affected by this. Since, after this, there would be no difference between using `nm_vac` and `nm`.

@erwanp how would you like me to go about with this?

**Comment by erwanp** [comment]
Actually, the error is elsewhere : 

wavenumbers/wavelengths are re-converted in the calc_spectrum function, without taking into account the propagation medium :  https://github.com/radis/radis/blob/develop/radis/lbl/calc.py#L482

All of this now happens in SpectrumFactory. 
- [L482-495](https://github.com/radis/radis/blob/develop/radis/lbl/calc.py#L482) are uncessary and could be removed. 
- Just forward the arguments wavenum_min/max, wavelength_min/max [to SpectrumFactory](https://github.com/radis/radis/blob/develop/radis/lbl/calc.py#L540)
- also, I noticed that [get_waverange()](https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L3231) should have `wunit=Default('cm-1')` as a main argument . You can fix it in the same PR.
