### ISSUE TITLE
Automatic wstep attribution in calc_spectrum()

### ISSUE THREAD

**Issue by CorentinGrimaldi** [radis/radis#250]
### What is currently done 
Currently the default "wstep" value is 0.01, so when executing the code below:
```
spec_h2o = calc_spectrum(wavelength_min=4195,
                         wavelength_max=4215,
                         Tgas=300,
                         pressure=1.01325,
                         mole_fraction=0.001,
                         molecule='H2O',
                         isotope='1,2,3,4',
                         path_length=1,
                         databank='hitran',
                         )
```
An AccuracyWarning is raised: 
"Some lines are too narrow (FWHM ~ 0.027 cm⁻¹) for the current spectral grid (wstep=0.01). Please reduce wstep to below 0.009 cm⁻¹. You can also ignore by setting `warnings={'AccuracyWarning':'ignore'}` (if you know what you're doing!)"

### 🎯 Describe what you'd like

The option to choose "auto" for wstep in the calc_spectrum() function. (Maybe update the default behavior to it)

Since the warning already give the value that is pertinent for the current case, the wstep="auto" option should just take it (0.009 in the example).

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
Yes !! It's already in #184 ,   but your explanation is better.

I'll close **the other one** as a duplicate ;)

**Comment by erwanp** [comment]
The only thing to choose is : **which number of points per line to enforce** ? 

To answer this question, eventually, we'll want to ensure a certain numerical error (note : eventually RADIS will have `performance/auto/precision` modes. The accepted error would be different for each. see the Discussion in https://github.com/radis/radis/discussions/197 )

1. For a perfect Voigt (numerical convolution), use different `wstep` and measure the error 
2. Multiply this by the linestrength to have an idea of the total error 
3. Determine the proper wstep !

**Comment by anandxkumar** [comment]
Hey @erwanp, the  `number of points per line to enforce` will directly relate to the adequate `wstep` for the line having minimum FWHM such that for a particular `number of wstep`  the `minimum_length` is sufficient enough to get good accuracy. For the precisions mode, we are talking about having an error threshold for each mode.
Suppose we are talking about `auto` mode. What we will want to do is find the numerical convolution of it using the broadening method = 'convolve' instead of the `olivero_1977` Voigt FWHM approximation, and get the error? 
Not sure how we will get the error from the Gaussian and Lorentzian HWHM.
After that, we multiply it with linestrength `S` and get the total error for different `wstep`. Depending on the value having the least error we will select that `wstep`.

**Comment by anandxkumar** [comment]
All the necessary checks can be added in the [_check_accuracy()](https://github.com/radis/radis/blob/180f63e4129c1307cd151f132f4342813c8ffbcd/radis/lbl/broadening.py#L876) function itself to recompute `wstep`. 
A simple approach will be manually defining the number of grid points per line for different modes like for 
`performance`  - `2 wstep /line`, for `auto` - `5 wstep/line`, etc. 
The method you have proposed will be more accurate per condition but we will have to make sure that all the checks aren't that computationally expensive.
Now about your idea, I have some doubts regarding the process. Depending on the `broadening method` selected we will have either Voigt HWHM or both Lorentzian and Gaussian HWHM. In default cases, we choose the `Voigt` method so sticking to that how we will calculate the error based on `wstep`?
