### ISSUE TITLE
Partial sum for faster noneq spectra

### ISSUE THREAD

**Issue by minouHub** [radis/radis#313]
Hello guys,
I'm trying to implement @dcmvdbekerom and @erwanp ideas to accelerate the computation of non-eq spectra: https://github.com/radis/radis-benchmark/blob/master/manual_benchmarks/fast-parsum.ipynb

I've been pulling my hair on the QDM method and gave up after 1.5 full day of trying to group correctly the vib levels and keep information on rot. I probably still have a lot to learn about pandas grouping.

So I switch to the @jit method for partial sums. Typical time for computing Q switches from 0.3 s to 0.1 s. So that's good. However, I realized (too late) that two essential quantities are also computed on the way: Qvib and dfQrot. Without them, impossible to compute the populations a bit later. Same problem will happen with the QDM method.

So I begin to think there is nothing to do to accelerate this computation, since we need the population at some point anyway... or you had something else in mind?

Minou

**Comment by erwanp** [comment]
Hello ! `Qvib` and `dfQrot` (Qrot for all vibrational bands) are really required only if you need to output the populations (to plot them). In practice that's never done; so we could skip it; and i think you started implementing it in #312 . 

To implement that, you need to change base.py (where populations are computed)
Instead of computing [nu_vib](https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L2474)
```python
df["nu_vib"] = df.gvibu / df.Qvib * exp(-hc_k * df.Evibu / Tvib)
```
you'll directly compute `nu_vib_Qvib` (nu_vib * Qvib)
```python
df["nu_vib_Qvib"] = df.gvibu * exp(-hc_k * df.Evibu / Tvib)
```
Same for Qrot. And therefore later, when [computing the total population](https://github.com/radis/radis/blob/develop/radis/lbl/base.py#L2509), you'll replace : 
```python
df["nu"] = df.nu_vib * df.nu_rot * (df.Qrotu * df.Qvib / df.Q)
```
with
```python
df["nu"] = df.nu_vib_Qvib * df.nu_rot_Qrot / df.Q
```

As @gagan-aryan knows, creating these extra columns `nu_vib_Qvib` and `nu_rot_Qrot` takes a lot of space (and times), so in the mode where populations are not returned, we could only create temporary numpy arrays, or even compute it directly. 

```python
if vib_distribution == "boltzmann" and rot_distribution == "boltzmann":
    df["nu"] = df.gvibu * exp(-hc_k * df.Evibu / Tvib) * df.grotu * exp(-hc_k * df.Erotu / Trot)  / df.Q
```

@gagan-aryan i'm also noticing in passing that df.Q still exists here as a column instead of as an attribute, is it already being fixed in a PR ?

**Comment by gagan-aryan** [comment]
Hey @erwanp !! I have not touched the implementation of the calculations of the population for the case of non_eq. So yes, the initial implementation of yours is what we still have in the codebase. We had decided on creating a separate POC for the case of non_eq and then implement it to codebase ( I have added a card regarding this in my project).

**Comment by erwanp** [comment]
Thanks for refreshing my memory! I had a look at the noneq implementation while working on #316.  It seems doable to remove all Qvib and dfQrot as @minouHub did in #312.  Check his implementation and you can (or him)  add a similar version on top of #316.

**Comment by erwanp** [comment]
#312 approach aborted, being replaced by #316 . Closing here
