### ISSUE TITLE
Parallel parsing of HITEMP Files

### ISSUE THREAD

**Issue by erwanp** [radis/radis#360]
### 🎯 Describe what you'd like

Fetch_hitemp currently takes ~ 1 hr to parse HITEMP H2O lines into HDF5 format. Can be made 4-5 times faster by CPU parallelization (easy given that H2O database is in multiple files).

Will prevent timeouts when setting up https://github.com/radis/radis-lab 

### 💡 Possible implementations

 
- Joblib ? See for instance [database.py](https://github.com/radis/radis/blob/710cd38f8349fde2db394f4c82e8d78886a1f6e5/radis/tools/database.py#L1141)

- Or [mpi4py examples](https://github.com/jbornschein/mpi4py-examples)

Changes should be injected in [download_and_parse](https://github.com/radis/radis/blob/bbd27b590c0c565f034bd9250f9aa9aee7de5bba/radis/io/dbmanager.py#L257)

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by brendandrury** [comment]
I'd like to try my hand at this with joblib if no one's started on it, as the actual parallelization change seems trivial by just adapting the code from database.py. However, I think [parse_to_local_file's progress meter code](https://github.com/radis/radis/blob/bbd27b590c0c565f034bd9250f9aa9aee7de5bba/radis/io/hitemp.py#L352) won't work if the function is run by multiple cores; the processes will each print their own progress over each other. One idea I had for this would be to use a subprocess.queue to share progress between processes and then have only 1 in nJobs processes actually print progress, but that's not as straightforward to implement and there would still be issues with the wavenumber ranges. I could also just disable the progress bar entirely, since the print statements would still provide a (less precise) measure of how much has been downloaded. 

Any thoughts?

**Comment by erwanp** [comment]
Hello! Parsing of a database is usually only done once per user, so we should put minimal effort in how it's done : skipping the internal progress bar in parallel mode as you suggest is a very good compromise. Do you need help to get started?
