### ISSUE TITLE
wstep='auto' fails for multiple molecules

### ISSUE THREAD

**Issue by erwanp** [radis/radis#381]
### 🐛 Describe the bug

'auto' mode doesn't work with multiple molecules. Crashes Radis-app  https://github.com/suzil/radis-app/issues/463 

### 🖥 Steps To Reproduce

```python
from radis import calc_spectrum
s = calc_spectrum(1900, 2300,         # cm-1
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction={"CO":0.1, "CO2":0.1},
                  path_length=1,      # cm
                  wstep='auto',
                  databank='hitran',  # or use 'hitemp'
                  )
```
Raises:
```
  File "d:\github\radis\radis\lbl\calc.py", line 482, in calc_spectrum
    s = MergeSlabs(*s_list)

  File "d:\github\radis\radis\los\slabs.py", line 658, in MergeSlabs
    slabs = resample_slabs(

  File "d:\github\radis\radis\los\slabs.py", line 438, in resample_slabs
    raise ValueError(

ValueError: All wavelengths/wavenumbers must be the same for multi slabs configurations. Consider using `resample='intersect'` or `resample='full'`
```

### 💡 Possible solutions

@anandxkumar we could simply use "resample='intersect'" in `s = MergeSlabs(*s_list)` (calc.py, l482).
However it may be more efficient to already generate the spectra with the same spectral range (even if the resolution is too high for some of them), to avoid later interpolations. We could : 
- either evaluate the best wstep for all spectra before computing them, but that requires some refactoring. Let's not.
- or, in the loop over all spectra in calc.py, send something like "(wstep_last_spectrum, 'auto')", evaluated as "_take the minimum of wstep_last_spectrum, and the value you'll find with 'auto'_". Should be easier to implement, and at least if you happen to need a high resolution spectrum all the subsequent spectra will be computed with the same high resolution.  

Can you think of another way?

**Comment by anandxkumar** [comment]
Just a doubt, let us suppose a scenario, for 1st spectrum we have wstep = 0. 5, for second 0.4, and for a third spectrum 0.3
Since we are choosing min(wstep_prev, 'auto'), initially `wstep = 0.5` and 1st spectrum gets appended using 0.5, then for the 2nd spectrum, wstep will get updated to 0.4, so for `s2` wstep = 0.4, similarly `s3` wstep =0.3

now each spectrum has a different wstep value, which will give rise to the same error. And again we will have to use `resample='intersect'` to resolve it. The advantage of this method will be that there will be fewer interpolations.
