### ISSUE TITLE
🚀 Feature: accelerate partition function calculations

### ISSUE THREAD

**Issue by Rockyuo666** [radis/radis#550]
### 🔖 Feature description

How to accelerate the compute time when I use radis for multi spectrum calculating with different Tvib、Trot、mole fraction and pressure? The time of Calculated nonequilibrium populations and Checked nonequilibrium parameters cost much time when running, How can I reduce its time.

### 👉 Why you want this feature!!

I want to use radis for multiprocessing computeing for different spectrum, but the time consuming is unacceptable.

**Comment by erwanp** [comment]
Hello! There can be two sources of performance cost : 
- fetching energies to augment the database for non LTE parameters 
- then partition functions will be the limiting factor in your case, because unlike under equilibrium they cannot be tabulated

Good news, we have already worked on this : 
- by using a SpectrumFactory for batch processing, the energies will be fetched only once
- last year we implemented an "on the fly tabulation" of non equilibrium partitiob functions.

By using both batch processing non LTE spectra should be almost as fast as equilibrium. 

I can't remember the commands top of my head, have a look into the docs, also see #316

**Comment by erwanp** [comment]
Hello @Rockyuo666 can you share your input script ?

**Comment by minouHub** [comment]
@Rockyuo666, I tried the following example and it worked. Are you still having performance issues or bugs?
```python
from radis import SpectrumFactory

wmin, wmax = 2383.8, 2384.9
sf = SpectrumFactory(wavenum_min=wmin,
                     wavenum_max=wmax,
                      molecule='CO2',
                     isotope='1',
                     truncation=2.5,  # cm-1
                     medium='air',   
                     path_length=10.32, #cm
                     wstep=0.001, 
                     )
conditions = {'mole_fraction':0.2, 'pressure':1,
              'Ttrans':2000, 'Trot':2100, 'Tvib':1500}


sf.verbose = 3
# sf.load_databank("HITEMP-CO2-TEST") # my personal database
sf.fetch_databank("hitemp", load_columns='noneq') # my personal database
sf.df0.drop(sf.df0.index[sf.df0['v1u']==-1], inplace=True)
s = sf.non_eq_spectrum(**conditions)  # initialize energies, etc.
s.plot('absorbance')
```

**Comment by minouHub** [comment]
Issue closed because there is currently no way to reproduce the bug. Do not hesitate to re-open if needed
